#!/bin/bash

set -eu

HELPSTR="\
Usage:\n\
setup_bench <num_subcircuits> <num_sha2_iters> <num_portals>\
"

if [ -z ${1+x} ] || [ -z ${2+x} ] || [ -z ${3+x} ]; then
    echo -e "$HELPSTR"
    exit 1
fi

NUM_SUBCIRCUITS=$1
NUM_SHA2_ITERS=$2
NUM_PORTALS=$3

# nc=num subcircuits, ns=num sha2 iters, np=num portals
JOB_DESC="nc=${NUM_SUBCIRCUITS}_ns=${NUM_SHA2_ITERS}_np=${NUM_PORTALS}"

DATETIME=$(printf '%(%Y%m%d.%H%M%S)T\n' -1)
LOG_OUT="setup_out-${JOB_DESC}-${DATETIME}.txt"
LOG_ERR="setup_err-${JOB_DESC}-${DATETIME}.txt"
KEYFILE_OUT="pks-${JOB_DESC}.bin"


srun \
	--time 1:00:00 \
	--account imiers-prj-cmsc \
       	--out=$LOG_OUT \
	--error=$LOG_ERR \
	--ntasks=1 \
	--mem-per-cpu=4000 \
	--cpus-per-task=128 \
	setup_task.sh $NUM_SUBCIRCUITS $NUM_SHA2_ITERS $NUM_PORTALS $KEYFILE_OUT
