[package]
name = "tinyram_isa"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "assembler"

[dependencies]
bitfield = "0.14"
pest = "2.4.0"
pest_derive = "2.4.0"

[dev-dependencies]
rand = { version = "0.8", features = ["std"] }
